services:
  - type: web
    name: express-yandex-smart-home
    runtime: docker
    region: frankfurt
    plan: starter
    dockerfilePath: expressServer/Dockerfile
    numInstances: 1

    healthCheckPath: '/'
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MQTT_URL
        sync: false
